# to get tsocks to work on termux, add this to config.fish:
#
# set -xU LD_PRELOAD $LD_PRELOAD /data/data/com.termux/files/usr/lib/libtsocks.so
# set -e LD_PRELOAD


path {
	reaches = 10.77.0.0/255.255.0.0
	server = 127.0.0.1
	server_port = 1080 
	server_type = 5
}

# use direct connections for everything else
fallback = yes
