#!/bin/sh

# symlink me to ~/.xinitrc

xrdb -merge "$HOME/.Xresources"

xset -b # no bell

xset r rate 200 60 # keyboard repeat rate
# setxkbmap us -variant mac -option ctrl:nocaps # <-- set by system.scm

xset s off # screen saver
xset dpms 5600 5600 5600 # screen power saving

# xsetroot -cursor_name left_ptr # change mouse cursor

xrandr --output DP-1 --left-of HDMI-1 --auto



exec ssh-agent i3
