#!/gnu/store/k66i68s5l93n1lgxp29vn2292nsywp1v-bash-minimal-5.2.37/bin/sh --
# sx - start an xserver
# requires /gnu/store/bdk56akcs3fl9h390p92q724jvbqrqa4-xauth-1.1.3/bin/xauth Xorg /dev/urandom

cleanup() {
    if [ "$pid" ] && kill -0 "$pid" 2> /dev/null; then
        kill "$pid"
        wait "$pid"
        xorg=$?
    fi

    if ! stty "$stty"; then
        stty sane
    fi

    /gnu/store/bdk56akcs3fl9h390p92q724jvbqrqa4-xauth-1.1.3/bin/xauth remove :"$tty"

    if [ "$1" = exit ]; then
        exit "${xorg:-0}"
    fi
}

stty=$(stty -g)
tty=$(tty)
tty=${tty#/dev/tty}

cfgdir=${XDG_CONFIG_HOME:-$HOME/.config}/sx
datadir=${XDG_DATA_HOME:-$HOME/.local/share}/sx
mkdir -p -- "$cfgdir" "$datadir"

export XAUTHORITY="${XAUTHORITY:-$datadir/xauthority}"
touch -- "$XAUTHORITY"

/gnu/store/bdk56akcs3fl9h390p92q724jvbqrqa4-xauth-1.1.3/bin/xauth add :"$tty" MIT-MAGIC-COOKIE-1 "$(od -An -N16 -tx /dev/urandom | tr -d ' ')"

trap 'cleanup; trap - INT; kill -INT "$$"' INT
trap 'cleanup exit' EXIT HUP TERM QUIT

# Xorg will check whether it inherited a USR1 with a disposition of SIG_IGN and
# use this state to reply back to the parent process with its own USR1.
# This is done to indicate that the server is ready to accept connections.
# Taking advantage of this feature allows launching the client directly from a
# USR1 signal trap which obviates the need to poll for server readiness.
trap 'DISPLAY=:$tty exec "${@:-$cfgdir/sxrc}" & wait "$!"' USR1

(trap '' USR1 && exec Xorg :"$tty" -config xorg.conf -keeptty vt"$tty" -noreset -auth "$XAUTHORITY") & pid=$!
wait "$pid"
