Section "Files"
  FontPath "/gnu/store/apgplc23kh60xl2ga3flgl4k9lj10bva-font-gnu-unifont-16.0.02"
  FontPath "/gnu/store/i5nyvvzqn02rmjpw2z7dkhzqir4qgp69-font-terminus-4.49.1"
  FontPath "/gnu/store/xp0ksknh7ry3671cfj0i0j410s3p0zcy-font-alias-1.0.5/share/fonts/X11/75dpi"
  FontPath "/gnu/store/xp0ksknh7ry3671cfj0i0j410s3p0zcy-font-alias-1.0.5/share/fonts/X11/100dpi"
  FontPath "/gnu/store/xp0ksknh7ry3671cfj0i0j410s3p0zcy-font-alias-1.0.5/share/fonts/X11/misc"
  FontPath "/gnu/store/xp0ksknh7ry3671cfj0i0j410s3p0zcy-font-alias-1.0.5/share/fonts/X11/cyrillic"
  FontPath "/gnu/store/spbq1596118zpz610x2szvr0xgjwzl18-font-misc-misc-1.1.3/share/fonts/X11/misc"
  FontPath "/gnu/store/f9xnlmzm29p5mg4qdw2xpammw7sl4d68-font-adobe75dpi-1.0.4/share/fonts/X11/75dpi"

  ModulePath "/gnu/store/a64wn1rgqn163dmf8s2asi9169pazbmc-xf86-input-libinput-1.5.0/lib/xorg/modules/input"
  ModulePath "/gnu/store/6w1kw3aw2n45dgrdi9gylnxc0lpgjl4s-xf86-input-evdev-2.11.0/lib/xorg/modules/input"
  ModulePath "/gnu/store/lab0qxlj9m86fxkwj5yinjz02w3xjvg8-xf86-input-mouse-1.9.5/lib/xorg/modules/input"
  ModulePath "/gnu/store/a54zw2n52ic20sdrqa7hyf8n7z0ni6vj-xorg-server-21.1.21/lib/xorg/modules/drivers"
  ModulePath "/gnu/store/a54zw2n52ic20sdrqa7hyf8n7z0ni6vj-xorg-server-21.1.21/lib/xorg/modules/input"
  ModulePath "/gnu/store/a54zw2n52ic20sdrqa7hyf8n7z0ni6vj-xorg-server-21.1.21/lib/xorg/modules/extensions"
  ModulePath "/gnu/store/a54zw2n52ic20sdrqa7hyf8n7z0ni6vj-xorg-server-21.1.21/lib/xorg/modules"
EndSection

Section "ServerFlags"
  Option "AllowMouseOpenFail" "on"
EndSection



Section "InputClass"
  Identifier "evdev keyboard catchall"
  MatchIsKeyboard "on"
  Option "XkbLayout" "us"  Option "XkbVariant" "mac"  Option "XkbOptions" "ctrl:nocaps"

  MatchDevicePath "/dev/input/event*"
  Driver "evdev"
EndSection

