icons = "awesome5"

[theme]
# name = "dracula"

[theme.overrides]
idle_bg = "#222222"
idle_fg = "#e0e0e0"

[[block]]
block = "sound"
# format = "{volume:5#110} {volume:3}"

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization}"
info = 20 # above this >, turns blue

[[block]]
block = "temperature"
chip = "*-isa-*"
format = "{average:1}"
# collapsed = false
good = 25
idle = 40
info = 55
warning = 65

[[block]]
block = "disk_space"
path = "/"
format = "{icon}{available}"
unit = "GB"
alert_absolute = true
interval = 3
warning = 8 # bg orange
alert = 2 # bg red

[[block]]
block = "custom"
command = "printf '/raid ' ; df -BG /raid/ --output=avail | tail -n1"
#on_click = "sh -e 'sudo umount /paid ; mount.sshfs pisa:/raid/ /paid/'"
interval = 6

[[block]]
block = "memory"
display_type = "memory"
icons = true
format_mem = "{mem_used}"
format_swap = "swap: {swap_used}"
warning_mem = 60
critical_mem = 80

[[block]]
block = "net"
format = "{ip}{speed_up:5;M}{speed_down:5;M}"

[[block]]
block = "time"
interval = 1
format = "%a %Y-%m-%d %H:%M:%S"
